//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemystifyFema.Service.Models
{
    using System;
    
    public partial class SubscriptionPackageGet_Result6
    {
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public decimal PackageAmount { get; set; }
        public bool IsActive { get; set; }
        public string PackageDetail { get; set; }
    }
}
